### ISSUE TITLE
cannot load such file -- util (LoadError)

### ISSUE THREAD

**Issue by voxik** [ruby/chkbuild#28]
I am trying to establish Ruby CI for Fedora using Fedora's Jenkins instance. What puzzles me is that the test runs quite often fails with errors such as [1]:

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- util (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /chkbuild/chkbuild.rb:53:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
    from start-build:37:in `<main>'
```

This looks to me as some race condition. Any hint what could be the real reason behind?

[1] http://jenkins.fedorainfracloud.org/job/ruby-chkbuild/588/label=F22/console

**Comment by hsbt** [comment]
`ruby start-build` is working with my environment and I can't access https://jenkins-fedora-infra.apps.ci.centos.org/job/ruby-chkbuild/588/label=F22/console. 

I'm closing this.
